

var DATA_SECTION = [
	[SECTION_ID_WEBSITE		,'綜合']
	,[SECTION_ID_SOCIAL		,'社群']
	,[SECTION_ID_GAME		,'遊戲']
	,[SECTION_ID_AV			,'影音']
	,[SECTION_ID_SHOPPING		,'購物']
	,[SECTION_ID_TV			,'電視']
	,[SECTION_ID_MOBILE		,'手機']
	,[SECTION_ID_FASHION		,'時尚']
	,[SECTION_ID_TRAVEL		,'旅遊']
	,[SECTION_ID_FREE		,'免費']
	,[SECTION_ID_APPLICATION	,'程式']
];

/* ========================================================================== */

var DATA_WEBSITE = [
	['website-portal'		,'入口'			,[
		['Yahoo奇摩'			,'https://tw.yahoo.com/']
		,['PChome'			,'http://www.pchome.com.tw/']
		,['Facebook'			,'https://www.facebook.com/']
		,['Youtube'			,'https://www.youtube.com/']
		,['Google'			,'https://www.google.com.tw/']
		,['巴哈姆特'			,'http://www.gamer.com.tw/']
		,['遊戲基地'			,'http://www.gamebase.com.tw/']
		,['百度'			,'http://www.baidu.com/']
	]]
	,['website-news'		,'新聞'			,[
		['蘋果日報'			,'http://www.appledaily.com.tw/']
		,['聯合新聞網'			,'http://udn.com/news/index']
		,['今日新聞'			,'http://www.nownews.com/']
		,['東森新聞雲'			,'http://www.ettoday.net/']
		,['中時電子報'			,'http://www.chinatimes.com/']
		,['中央通訊社'			,'http://www.cna.com.tw/']
		,['三立新聞網'			,'http://www.setn.com/']
		,['公民新聞'			,'http://www.peopo.org/']
	]]
	,['website-life'		,'生活'			,[
		['中央氣象局'			,'http://www.cwb.gov.tw/']
		,['台灣彩券'			,'http://www.taiwanlottery.com.tw/']
		,['統一發票'			,'http://invoice.etax.nat.gov.tw/']
		,['165全民防騙超連結'		,'http://165.gov.tw/']
		,['臺灣鐵路管理局'		,'http://www.railway.gov.tw/tw/']
		,['台灣高鐵'			,'http://www.thsrc.com.tw/']
		,['中華郵政'			,'http://www.post.gov.tw/']
	]]
	,['website-government'		,'政府機關'		,[
		['財政部稅務入口網'		,'http://www.etax.nat.gov.tw/']
		,['勞動部勞工保險局'		,'http://www.bli.gov.tw/']
		,['中央健康保險署'		,'http://www.nhi.gov.tw/']
		,['全國法規資料庫'		,'http://law.moj.gov.tw/']
		,['經濟部智慧財產局'		,'http://www.tipo.gov.tw/']
	]]
	,['website-comin'		,'動漫'			,[
		['無限動漫'			,'http://www.8comic.com/']
		,['動漫狂'			,'http://www.cartoonmad.com/']
		,['動漫戲說'			,'http://comic.acgn.cc/']
		,['九九漫畫'			,'http://www.99comic.com/']
		,['暗暗漫畫'			,'http://aacomic.com/']
		,['17KK.cc'			,'http://www.17kk.cc/']
		,['無憂漫畫'			,'http://www.blgl8.com/']
		,['笨狗漫畫'			,'http://www.bengou.com.tw/']
	]]
	,['website-3c'			,'3C'			,[
		['Engadget 中文版'		,'http://chinese.engadget.com/']
		,['挨踢路人甲'			,'http://walker-a.com/']
		,['電腦王阿達的3C胡言亂語'	,'http://www.kocpc.com.tw/']
		,['癮科技'			,'http://www.cool3c.com/']
		,['鄭蛋蛋的3C評測站'		,'http://egg3c.tw/']
		,['VR-Zone 中文版'		,'http://chinese.vr-zone.com/']
		,['T客邦'			,'http://www.techbang.com/']
		,['硬是要學'			,'http://www.soft4fun.net/']
		,['老貓測3C'			,'http://iqmore.tw/']
		,['就是教不落'			,'http://steachs.com/']
		,['Qooah'			,'http://qooah.com/']
		,['3C新報'			,'http://3c.technews.tw/']
	]]
	,['website-job'			,'求職'			,[
		['yes123求職網'			,'https://www.yes123.com.tw/']
		,['104人力銀行'			,'http://www.104.com.tw/']
		,['111人力銀行'			,'http://www.1111.com.tw/']
		,['518人力銀行'			,'http://www.518.com.tw/']
		,['178人力銀行'			,'http://www.job178.com.tw/']
		,['080人力銀行'			,'http://080job.com/']
		,['MyJob人力銀行'		,'http://www.myjob.com.tw/']
	]]
	,['website-house'		,'房屋'			,[
		['實價查詢服務網'		,'http://lvr.land.moi.gov.tw/']
		,['信義房屋'			,'http://www.sinyi.com.tw/']
		,['永慶房仲網'			,'http://www.yungching.com.tw/']
		,['591房屋交易'			,'http://www.591.com.tw/']
		,['東森房屋'			,'http://www.etwarm.com.tw/']
		,['台灣房屋'			,'http://www.twhg.com.tw/']
		,['太平洋房屋'			,'http://www.pacific.com.tw/']
		,['住商不動產'			,'http://www.hbhousing.com.tw/']
		,['21世紀不動產'		,'http://www.century21.com.tw/']
	]]
	,['website-scan-file'		,'線上掃檔'		,[
		['VirusTotal'			,'https://www.virustotal.com/zh-tw/']
		,['Jotti'			,'http://virusscan.jotti.org/en']
		,['VirSCAN'			,'http://www.virscan.org/']
		,['COMODO'			,'http://camas.comodo.com/']
		,['Dr.WEB'			,'http://www.drweb-online.com/en/online_check.asp']
		,['Metascan'			,'https://www.metascan-online.com/']
		,['FortiGuard'			,'http://www.fortiguard.com/antivirus/virus_scanner.html']
	]]
	,['website-google'		,'Google'	,[
		['地圖'				,'https://maps.google.com.tw/']
		,['翻譯'			,'https://translate.google.com.tw/']
		,['Gmail'			,'https://mail.google.com/']
	]]
];

/* ========================================================================== */

var DATA_AV = [
	['av-video'			,'影片'			,[
		['Youtube'			,'https://www.youtube.com/']
		,['土豆'			,'http://www.tudou.com/']
		,['優酷'			,'http://www.youku.com/']
		,['搜狐視頻'			,'http://tv.sohu.com/']
		,['騰訊視頻'			,'http://v.qq.com/']
		,['愛奇藝'			,'http://www.iqiyi.com/']
		,['樂視網'			,'http://www.letv.com/']
		,['Vimeo'			,'https://vimeo.com/']
		,['PPTV'			,'http://www.pptv.com/']
	]]
	,['av-live'			,'直播'			,[
		['Witch'			,'http://www.twitch.tv/']
		,['Piko'			,'http://tw.pikolive.com/']
		,['LIVEhouse'			,'https://livehouse.in/']
		,['天天直播 (運動)'		,'http://www.tiantian.tv/']
		,['Garena (遊戲)'		,'http://live.garena.tw/']
		,['HOP Sports (運動)'		,'http://sports.hoptv.tw/web/']
		,['球吧網 (運動)'		,'http://www.ballbar.cc/']
		,['A直播 (運動)'		,'http://www.azhibo.com/']
	]]
	,['av-audio'			,'音樂'			,[
		['HiNet 廣播'			,'http://hichannel.hinet.net/radio/index.do']
		,['Grooveshark'			,'http://grooveshark.com/']
		,['網易雲音樂'			,'http://music.163.com/']
		,['Spotify'			,'https://play.spotify.com/']
		,['Baidu音樂'			,'http://music.baidu.com/']
		,['搜狗音樂'			,'http://123.sogou.com/ting/']
	]]
];	

/* ========================================================================== */

var DATA_GAME = [
	['game-sports'			,'電競'			,[
		['TeSL'				,'http://www.esports.com.tw/']
		,['台灣星盟電競情報網'		,'http://sc2clan.tw/']
		,['Garena'			,'http://lol.esport.garena.tw/index/']
		,['ESR電競王'			,'http://www.esranking.com/']
		,['4Gamers'			,'http://www.4gamers.com.tw/']
		,['eGamers'			,'http://sc2.egamers.tw/']
		,['Gaming'			,'http://www.gaming.com.tw/']
	]]
	,['game-live'			,'直播'			,[
		['台灣星盟電競情報網'		,'http://sc2clan.tw/lives']
		,['Garena'			,'http://live.garena.tw/']
		,['TeSL (HiNet)'		,'http://www.esports.com.tw/Live/HiNet.html']
		,['TeSL (twitch)'		,'http://www.esports.com.tw/Live/twitch.html']
		,['TeSL Channel'		,'https://www.youtube.com/user/lootowinds']
		,['遊戲大亂鬥'			,'http://www.league-funny.com/']
	]]
	,['game-small'			,'小遊戲'		,[
		['史萊姆好玩遊戲'		,'http://game.slime.com.tw/']
		,['遊戲天堂'			,'http://i-gamer.net/']
		,['woGames'			,'http://www.wogames.com/']
		,['小遊戲天堂'			,'http://my-gamer.com/']
		,['小遊戲天堂'			,'http://www.yosegame.com/']
		,['QK3000'			,'http://www.qk3000.com/']
		,['小遊戲客棧'			,'http://gamekz.com/']
		,['GaGaMeMe'			,'http://www.gagameme.com/tw/']
		,['小遊戲谷'			,'http://gamekuo.com/']
		,['遊戲泡麵'			,'http://easygame.tw/']
		,['艾可小遊戲'			,'http://www.okokgame.com/']
		,['遊戲圈小遊戲'		,'http://www.gameso.cc/']
		,['免費遊戲網'			,'http://www.freegame.tw/']
		,['遊戲桃'			,'http://www.gamesmomo.com/']
		,['安安遊戲網'			,'http://anan.game.tw/']
		,['遊戲鍋'			,'http://www.gj1904.com/']
		,['東方娃娃學園'		,'http://www.qqschool.com.tw/']
		,['線上遊戲俱樂部'		,'http://www.olgclub.com/']
		,['遊戲世界'			,'http://i-gameworld.com/']
	]]
	,['game-merchandise'		,'交易'		,[
		['8591寶物交易'			,'http://www.8591.com.tw/']
		,['9199交易久久'		,'https://www.9199.com.tw/']
		,['i7391輕鬆交易網'		,'http://www.i7391.com/']
	]]
];

/* ========================================================================== */

var DATA_FREE = [
	['free-email'			,'信箱'			,[
		['Yahoo奇摩電子信箱'		,'https://tw.mail.yahoo.com/']
		,['Gmail'			,'https://mail.google.com/']
		,['PChome 電子郵件'		,'http://mail.pchome.com.tw/']
		,['Outlook'			,'http://outlook.com/']
	]]
	,['free-droped-email'		,'拋棄式信箱'		,[
		['Guerrilla'			,'https://www.guerrillamail.com/zh-hant/']
		,['十分鐘電郵'			,'http://10minutemail.com/']
		,['Mailnesia'			,'http://mailnesia.com/zh/']
		,['FakeInbox'			,'http://www.fakeinbox.com/']
		,['Disposable Temporary'	,'http://tempemail.gentleprojects.com/']
		,['Jetable'			,'http://www.jetable.org/zh/index']
	]]
	,['free-space'			,'空間'			,[
		['Google Drive'			,'https://drive.google.com/']
		,['DropBox'			,'https://www.dropbox.com/']
		,['OneDrive'			,'https://onedrive.live.com/']
		,['Hami+ 個人雲'		,'https://hamicloud.net/']
		,['MEGA'			,'https://mega.co.nz/']
		,['MediaFire'			,'https://www.mediafire.com/']
		,['Minus'			,'http://minus.com/']
		,['GE.TT'			,'http://ge.tt/']
		,['FunP.Net'			,'http://www.funp.net/']
		,['百度雲網盤'			,'http://pan.baidu.com/']
		,['FreakShare'			,'http://freakshare.com/']
	]]
	,['free-image'			,'圖床'			,[
		['Flickr'			,'https://www.flickr.com/']
		,['Imgur'			,'http://imgur.com/']
		,['ThumbSnap'			,'http://thumbsnap.com/']
		,['PhotoBucket'			,'http://photobucket.com/']
		,['微圖床'			,'http://up.twblog.org/']
		,['PicSpy'			,'http://picspy.info/']
		,['FotoPu'			,'http://www.fotopu.com/']
	]]
];

/* ========================================================================== */

var DATA_SOCIAL = [
	['social-social'		,'社交'			,[
		['Facebook'			,'https://www.facebook.com/']
		,['Twitter'			,'https://twitter.com/']
		,['PLURK'			,'http://www.plurk.com/']
		,['Instagram'			,'https://instagram.com/']
		,['痞客邦'			,'https://www.pixnet.net/']
		,['微博'			,'http://tw.weibo.com/']
		,['Tumblr'			,'https://www.tumblr.com/']
		,['Google+'			,'https://plus.google.com']
	]]
	,['social-forum'		,'論壇'			,[
		['批踢踢實業坊'			,'https://www.ptt.cc/']
		,['Mobile01'			,'http://www.mobile01.com/']
		,['卡提諾論壇'			,'http://ck101.com/']
		,['捷克論壇'			,'http://www.jkforum.net/']
		,['伊莉討論區'			,'http://www.eyny.com/']
	]]
	,['social-article'		,'文章'			,[
		['愛評網'			,'http://www.ipeen.com.tw/']
		,['卡卡洛普'			,'http://www.gamme.com.tw/']
		,['LIFE'			,'http://www.life.com.tw/']
		,['BuzzHand'			,'http://www.buzzhand.com/']
		,['BuzzOrange'			,'http://buzzorange.com/']
		,['PPT01'			,'http://ptt01.cc/']
		,['愛瘋誌'			,'http://www.myapp.com.tw/']
		,['iBEAUTY'			,'http://ibeauty.tw/']
		,['泛科學'			,'http://pansci.tw/']
		,['GigaCircle'			,'http://tw.gigacircle.com/']
		,['爆報'			,'http://powpost.com/']
		,['reBuzz'			,'http://rebuzz.tw/']
		,['TEEPR'			,'http://www.teepr.com/']
		,['VAN698'			,'http://www.van698.com/']
		,['熱新聞'			,'http://yes-news.com/']
	]]
	,['social-quiz'			,'測驗'			,[
		['心樂園'			,'http://www.heartfun.net/']
		,['ZUOPY'			,'http://www.zuopy.com/']
		,['QQbuzz'			,'http://tw.qqbuzz.com/']
	]]
];

/* ========================================================================== */

var DATA_SHOPPING = [
	['shopping-auction'		,'拍賣'			,[
		['Yahoo!奇摩拍賣'		,'https://tw.bid.yahoo.com/']
		,['露天拍賣'			,'http://www.ruten.com.tw/']
		,['eBay'			,'http://www.ebay.com.tw/']
		,['淘寶網台灣'			,'http://tw.taobao.com/']
		,['淘寶網'			,'http://www.taobao.com/']
	]]
	,['shopping-group'		,'團購'			,[
		['GROUPON'			,'http://www.groupon.com.tw/']
		,['夠麻吉'			,'http://www.gomaji.com/']
		,['17 Life'			,'http://www.17life.com/']
		,['123'				,'http://www.123.com.tw/']
		,['半價團購'			,'http://buy.goodlife.tw/']
		,['愛合購'			,'http://www.ihergo.com/']
	]]
	,['shopping-mall'		,'商城'			,[
		['Yahoo!奇摩購物中心'		,'https://tw.buy.yahoo.com/']
		,['PChome線上購物'		,'http://shopping.pchome.com.tw/']
		,['樂天'			,'http://www.rakuten.com.tw/']
		,['lativ'			,'http://www.lativ.com.tw/']
		,['東京著衣'			,'http://www.tokichoi.com.tw/']
		,['MODA'			,'http://www.modalovemoda.com/']
		,['GoHappy'			,'http://www.gohappy.com.tw/']
	]]
	,['shopping-tv'			,'電視'			,[
		['momo購物網'			,'http://www.momoshop.com.tw/']
		,['東森購物網'			,'http://www.etmall.com.tw/']
		,['viva'			,'https://www.vivatv.com.tw/']
		,['森森購物網'			,'http://www.u-mall.com.tw/']
	]]
];

/* ========================================================================== */

var DATA_MOBILE = [
	['mobile-rate'			,'費率'			,[
		['中華電信'			,'http://www.emome.net/']
		,['遠傳電信'			,'http://www.fetnet.net/']
		,['台灣大哥大'			,'https://www.taiwanmobile.com/']
		,['亞太電信'			,'http://www.aptg.com.tw/']
		,['台灣之星'			,'http://www.tstartel.com/']
	]]
	,['mobile-app'			,'APP'			,[
		['app01'			,'http://www.futago.com.tw/']
		,['app-island'			,'http://app-island.com/']
		,['我只推薦好app'		,'http://apps.friday.tw/news/']
		,['App Knob'			,'http://www.appknob.com/']
		,['Dr.愛瘋'			,'http://app.yipee.cc/']
		,['遊戲基地 Android'		,'http://android.zones.gamebase.com.tw/']
		,['遊戲基地 iPhone'		,'http://ios.zones.gamebase.com.tw/']
		,['App情報誌'			,'http://www.appshooting.com.tw/']
		,['App堂'			,'http://www.apptang.com/']
		,['愛應用'			,'http://www.iapps.im/']
   		,['Google play'			,'https://play.google.com/store']
   		,['Android 應用市場'		,'http://m.apk.tw/']
   		,['1Mobile'			,'http://www.1mobile.com.tw/']
	]]
	,['mobile-commit'		,'評測'			,[
		['手機網'			,'http://www.futago.com.tw/']
		,['TestFreaks'			,'http://www.testfreaks.tw/cell-phones/']
		,['ePrice'			,'http://www.eprice.com.tw/mobile/']
		,['手機王'			,'http://www.sogi.com.tw/mobile']
		,['3C Box'			,'http://smartphones.3cbox.net/']
	]]
	,['mobile-android-forum'	,'Android 論壇'		,[
		['Android 台灣中文網'		,'http://apk.tw/']
		,['手機巴士'			,'http://bbs.mpbus.com/']
		,['機鋒論壇'			,'http://bbs.gfan.com/']
		,['MyGPF'			,'http://gphonefans.net/forum.php']
		,['安卓網'			,'http://bbs.hiapk.com/']
		,['Android台灣部落'		,'http://droidtw.com/forum.php']
		,['91手機論壇'			,'http://ibbs.91.com/']
		,['Xda.cn'			,'http://bbs.xda.cn/']
		,['魔趣論壇'			,'http://bbs.mfunz.com/']
		,['力卓'			,'http://bbs.lidroid.com/']
		,['安卓公社s'			,'http://android.zone.it.sohu.com/forum.php']
		,['Mobile01'			,'http://www.mobile01.com/category.php?id=4']
		,['華碩產品討論區'		,'http://www.asus.com/zentalk/tw/forum.php?gid=1']
		,['MIUI官方論壇'		,'http://tw.miui.com/forum.php']
	]]
	,['mobile-iphone-forum'		,'iPhone 論壇'		,[
		['iPhone4.tw'			,'http://iphone4.tw/forums/forum.php']
		,['I樂園'			,'http://ifansland.com/forum.php']
		,['91手機論壇'			,'http://ibbs.91.com/']
		,['蘋果園論壇'			,'http://bbs.app111.com/']
		,['蘋果公社'			,'http://apple.zone.it.sohu.com/forum.php']
		,['Mobile01'			,'http://www.mobile01.com/category.php?id=15']
		,['iPhone專業手機論壇'		,'http://www.aiphn.com/']
		,['維維網'			,'http://bbs.appvv.com/']
		,['iPhone中文網'		,'http://iphone.tgbus.com/']
	]]
	,['mobile-vendor'		,'製造商'		,[
		['宏達電'			,'http://www.htc.com/tw/']
		,['華碩'			,'http://www.asus.com/tw/Phones/']
		,['宏碁'			,'http://www.acer.com.tw/ac/zh/TW/content/group/smartphones']
		,['Apple'			,'https://www.apple.com/tw/']
		,['三星'			,'http://www.samsung.com/tw/home']
		,['LG'				,'http://www.lg.com/tw/mobile-devices']
		,['SONY'			,'http://www.sonymobile.com/global-zh/']
		,['NOKIA'			,'http://www.microsoft.com/zh-tw/mobile/']
		,['InFocus'			,'http://www.infocusphone.com/tw/']
		,['小米'			,'http://www.mi.com/tw/']
		,['OPPO'			,'http://oppomobile.tw/']
		,['華為'			,'http://consumer.huawei.com/tw/']
	]]
	,['mobile-manage'			,'管理'			,[
		['iTunes'			,'https://www.apple.com/tw/itunes/download/']
		,['iTools'			,'http://tw.gashplus.com/iTools/']
		,['iFunBox'			,'http://www.i-funbox.com/']
		,['碗豆莢'			,'http://www.wandoujia.com/']
		,['應用寶'			,'http://sj.qq.com/']
		,['SynciOS'			,'http://www.syncios.com/tw/']
		,['MoboRobo'			,'http://www.moborobo.com/']
	]]
];

/* ========================================================================== */

var DATA_FASHION = [
	['fashion-news'			,'新聞'			,[
		['名人時尚'			,'http://ent.appledaily.com.tw/enews/fashion']
		,['樂時尚'			,'http://www.styletc.com/']
		,['HYPEBEAST'			,'http://cn.hypebeast.com/']
		,['女人迷'			,'http://womany.net/']
		,['A Day'			,'http://www.adaymag.com/']
		,['PopDaily'			,'http://www.popdaily.com.tw/']
	]]
	,['fashion-magamize'		,'雜誌'			,[
		['薇薇女性雜誌'			,'http://www.vvshu.com/']
	]]
	,['fashion-beauty'		,'美妝'			,[
		['UrCosme'			,'http://www.urcosme.com/']
		,['美妝邦'			,'http://fashion.piliapp.com/']
		,['iSwii'			,'http://www.iswii.net/']
		,['UNT'				,'http://www.shopunt.com/']
		,['VOCE'			,'http://voceblog.spp.com.tw/']
		,['美妝教主'			,'http://www.beautyblog.com.tw/']
		,['美周報'			,'https://www.ibeautyreport.com/']
		,['美容彩妝'			,'https://www.pixnet.net/blog/articles/category/23']
	]]
	,['fashion-dress'		,'穿搭'			,[
		['dappei'			,'http://dappei.com/']
		,['FashionGuide'		,'http://www.fashionguide.com.tw/']
		,['VOGUE'			,'http://www.vogue.com.tw/']
		,['這樣變型男'			,'http://mf.techbang.com/']
		,['GQ'				,'http://www.gq.com.tw/']
		,['Gentry'			,'http://www.gentry.com.tw/']
		,['時尚網'			,'http://www.trends.com.cn/']
		,['TSFM'			,'http://www.tsfm.tw/']
		,['O SHa\' Re'			,'http://www.oshare.com.tw/']
		,['今日我最潮'			,'http://yahoo-myshow.tumblr.com/']
		,['瘋穿搭'			,'http://www.dressie.com.tw/']
		,['JUKSY'			,'http://www.juksy.com/']
	]]
];

/* ========================================================================== */

var DATA_TRAVEL = [
	['travel-describe'		,'介紹'			,[
		['玩全台灣'			,'http://okgo.tw/']
		,['旅遊資訊王'			,'http://travel.network.com.tw/']
		,['四方通行'			,'http://guide.easytravel.com.tw/']
		,['輕旅行'			,'http://travel.yam.com/']
		,['青青小熊'			,'http://yoke918.com/']
		,['MOOK景點家'			,'http://www.mook.com.tw/']
		,['Via\'s旅行札記'		,'http://viablog.okmall.tw/']
		,['青年旅遊網'			,'https://youthtravel.tw/']
	]]
	,['travel-traffic'		,'交通'		,[
		['臺灣鐵路管理局'		,'http://www.railway.gov.tw/tw/']
		,['台灣高鐵'			,'http://www.thsrc.com.tw/']
		,['ezTravel (機票比價)'		,'https://www.eztravel.com.tw/airticket/fit/']
		,['Skyscanner (機票比價)'	,'http://www.skyscanner.com.tw/']
		,['FunTime (機票比價)'		,'http://www.funtime.com.tw/oveticket/']
		,['背包客棧 (機票比價)'		,'http://www.backpackers.com.tw/forum/airfare.php']
		,['與我旅遊 (機票比價)'		,'http://www.wego.tw/flights']
	]]
	,['travel-hotel'		,'飯店'		,[
		['救國團青年活動中心'		,'http://www.cyh.org.tw/']
		,['trivago'			,'http://www.trivago.com.tw/']
		,['agoda'			,'http://www.agoda.com/zh-tw']
		,['Booking.com'			,'http://www.booking.com/index.zh-tw.html']
		,['HotelsCombined'		,'http://www.hotelscombined.com.tw/']
		,['FunTime (國內)'		,'http://www.funtime.com.tw/domhotel/']
		,['FunTime (國際)'		,'http://www.funtime.com.tw/ovehotel/']
		,['飯店比價王'			,'http://hotel.network.com.tw/comparison/']
		,['與我旅遊'			,'http://www.wego.tw/hotels']
		,['TripAdvisor'			,'http://www.tripadvisor.com.tw/']
	]]
];

/* ========================================================================== */

var DATA_TV = [
	['tv-internet'			,'網路'			,[
		['Go TV Show'			,'http://gotvshow.blogspot.tw/p/blog-page.html']
		,['VIGOR 網路電視'		,'http://vigortv.net/']
		,['iTVer'			,'http://tv.itver.cc/']
		,['IPTV網路電視'		,'http://iptv.tw/']
		,['Yahoo電視時刻表'		,'https://tw.movies.yahoo.com/tv_index.html']
		,['nio電視網節目表'		,'http://www.niotv.com/i_index.php?cont=day']
		,['Alway TV'			,'http://www.alway.tv/']
	]]
	,['tv-series'			,'追劇'			,[
		['Love TV Show'			,'http://www2.lovetvshow.com/']
		,['楓林網'			,'http://www.maplestage.com/']
		,['DramaQ 線上看'		,'http://www.dramaq.org/']
		,['FUN-TV'			,'http://www.fun-tv.net/']
		,['美酷劇場'			,'http://www.melkutv.org/']
		,['bananaido'			,'http://www.bananaidol.com/']
		,['愛看TV'			,'http://i-tv.com.tw/']
		,['風林網'			,'http://8drama.com/']
	]]
	,['tv-station'			,'電視台'		,[
		['民視'				,'http://www.ftv.com.tw/']
		,['台視'			,'http://www.ttv.com.tw/']
		,['中視'			,'http://www.ctv.com.tw/']
		,['華視'			,'http://www.cts.com.tw/']
		,['公共電視'			,'http://www.pts.org.tw/']
		,['三立電視台'			,'http://www.settv.com.tw/']
		,['八大電視台'			,'http://www.gtv.com.tw/']
		,['緯來電視網'			,'http://www.videoland.com.tw/']
		,['東森電視'			,'http://www.ebc.net.tw/']
		,['中天電視'			,'http://www.ctitv.com.tw/']
		,['TVBS'			,'http://www.tvbs.com.tw/']
		,['福斯國際電視網'		,'http://www.fictw.com/']
		,['壹電視'			,'http://www.nexttv.com.tw/']
		,['新唐人'			,'http://www.ntdtv.com/xtr/b5/tv.html']
	]]
	,['tv-youtube-live'		,'YouTube 直播'		,[
		['公共電視'			,'https://www.youtube.com/watch?v=bDxj3X2-Qgw']
		,['民視四季台'			,'https://www.youtube.com/watch?v=bGcUPN1GnBU']
		,['華視新聞台'			,'https://www.youtube.com/watch?v=YPaKDrB7kW4']
		,['民視交通台'			,'https://www.youtube.com/watch?v=VDlVuln9kwo']
		,['民視新聞台'			,'https://www.youtube.com/watch?v=XxJKnDLYZz4']
		,['UDN TV'			,'https://www.youtube.com/watch?v=SwrKzkRUlaw']
		,['中天新聞台'			,'https://www.youtube.com/watch?v=9ZQkD-gQGnw']
		,['大愛一台'			,'https://www.youtube.com/watch?v=ESKjSwcswBM']
		,['大愛二台'			,'https://www.youtube.com/watch?v=_bPfRt7HlxM']
		,['全大電視台'			,'https://www.youtube.com/watch?v=orMJ5yNFXOQ']
	]]
	,['tv-youtube-channel'		,'YouTube 頻道'		,[
		['緯來體育台'			,'https://www.youtube.com/user/vlsports']
		,['FOX SPORTS'			,'https://www.youtube.com/channel/UCeok_2fmVPaueGKX38Ixv2Q']
		,['三立財經台'			,'https://www.youtube.com/channel/UCoNYj9OFHZn3ACmmeRCPwbA']
		,['ELTA SPORTS'			,'https://www.youtube.com/user/ELTASPORTSHD']
	]]
	,['tv-taiwan'			,'頻道'			,[
		['[06] 民視'			,'rtmp/?[06] 民視|rtmp://119.81.141.200:1935/sat/tv05']
		,['[06] 民視'			,'hls/?[06] 民視|http://210.200.79.25:1935/live/ftvw_sp.sdp/chunklist.m3u8']
		,['[08] 台視'			,'rtmp/?[08] 台視|rtmp://149.3.141.210:1935/tv/ttv04']
		,['[08] 台視'			,'hls/?[08] 台視|http://210.200.79.25:1935/live/ttv.sdp/chunklist.m3u8']
		,['[09] 大愛'			,'https://www.youtube.com/watch?v=ESKjSwcswBM']
		,['[10] 中視'			,'rtmp/?[10] 中視|rtmp://149.3.141.210:1935/tv/ttv03']
		,['[10] 中視'			,'hls/?[10] 中視|http://210.200.79.25:1935/live/ctv.sdp/chunklist.m3u8']
		,['[12] 華視'			,'rtmp/?[12] 華視|rtmp://149.3.141.210:1935/tv/ttv08']
		,['[12] 華視'			,'hls/?[12] 華視|http://210.200.79.25:1935/live/cts.sdp/chunklist.m3u8']
		,['[22] Cartoon Network'	,'hls/?[22] Cartoon Network|http://210.200.79.25:1935/live/cncartoon_sp.sdp/chunklist.m3u8']
		,['[26] 緯來綜合台'		,'rtmp/?[26] 緯來綜合台|rtmp://119.81.141.201:1935/sat/tv26']
		,['[27] 八大第一台'		,'hls/?[27] GTV八大第一台|http://210.200.79.25:1935/live/gtv_sp.sdp/chunklist.m3u8']
		,['[28] 八大综合台'		,'rtmp/?[28] GTV八大综合台|rtmp://149.3.141.210:1935/tv/ttv07']
		,['[29] 三立台灣台'		,'rtmp/?[29] 三立台灣台|rtmp://119.81.141.201:1935/sat/tv29']
		,['[30] 三立都會台'		,'rtmp/?[30] 三立都會台|rtmp://149.3.141.210:1935/tv/ttv05']
		,['[36] 中天綜合台'		,'rtmp/?[36] 中天綜合台|rtmp://149.3.141.210:1935/tv/ttv13']
		,['[39] 中天娛樂台'		,'rtmp/?[39] 中天娛樂台|rtmp://119.81.141.201:1935/sat/tv39']
		,['[40] 東森戲劇台'		,'rtmp/?[40] 東森戲劇台|rtmp://149.3.141.210:1935/tv/ttv06']
		,['[42] TVBS歡樂台'		,'rtmp/?[42] TVBS歡樂台|rtmp://119.81.141.201:1935/sat/tv42']
		,['[49] 壹電視新聞台'		,'hls/?[49] 壹電視新聞台|http://wowza4.nexttv.com.tw/liveedge/eratv4/chunklist.m3u8']
		,['[51] 東森新聞台'		,'hls/?[51] 東森新聞台|http://210.200.79.25:1935/live/acti_sp.sdp/playlist.m3u8']
		,['[52] 中天新聞台'		,'https://www.youtube.com/watch?v=9ZQkD-gQGnw']
		,['[53] 民視新聞台'		,'https://www.youtube.com/watch?v=XxJKnDLYZz4']
		,['[55] TVBS新聞台'		,'hls/?[55] TVBS新聞台|http://210.200.79.25:1935/live/tvbsnhd/playlist.m3u8']
		,['[55] TVBS新聞台'		,'rtmp/?[55] TVBS新聞台|rtmp://149.3.141.210:1935/tv/ttv14']
		,['[56] TVBS'			,'hls/?[56] TVBS|http://210.200.79.25:1935/live/tvbs_sp.sdp/playlist.m3u8']
		,['[57] 東森財經台'		,'rtmp/?[57] 東森財經台|rtmp://119.81.141.197:1935/sat/tv57']
		,['[58] 非凡新聞台'		,'hls/?[58] 非凡新聞台|http://210.200.79.25:1935/live/ustvn_sp.sdp/playlist.m3u8']
		,['[61] 衛視電影台'		,'rtmp/?[61] 衛視電影台|rtmp://149.3.141.210:1935/tv/ttv15']
		,['[62] 東森電影台'		,'rtmp/?[62] 東森電影台|rtmp://149.3.141.210:1935/tv/ttv10']
		,['[71] 緯來育樂台'		,'rtmp/?[71] 緯來育樂台|rtmp://119.81.141.201:1935/sat/tv70']
		,['[72] 緯來體育台'		,'rtmp/?[72] 緯來體育台|rtmp://119.81.141.201:1935/sat/tv72']
		,['[75] 緯來日本台'		,'rtmp/?[75] 緯來日本台|rtmp://149.3.141.210:1935/tv/ttv09']
		,['[73] FOX SPORTS'		,'rtmp/?[73] FOX SPORTS|rtmp://119.81.141.201:1935/sat/tv73']
		,['[74] FOX SPORTS 2'		,'rtmp/?[74] FOX SPORTS 2|rtmp://119.81.141.201:1935/sat/tv74']
		,['[89] 非凡商業台'		,'hls/?[89] 非凡商業台|http://210.200.79.25:1935/live/ustvc_sp.sdp/playlist.m3u8']
		,['宏觀衛視'			,'hls/?宏觀衛視|http://mobile.ccdntech.com/live/_definst_/vod62_Live/live1/playlist.m3u8']
		,['東森亞洲台'			,'hls/?東森亞洲台|http://tw.stream.omc.hk:1935/live/acti_2_sp.sdp/chunklist.m3u8']
	]]
];

/* ========================================================================== */

var DATA_APPLICATION = [
	['application-communication'	,'通訊'			,[
		['LINE'				,'http://line.me/zh-hant/']
		,['Skype'			,'http://www.skype.com/zh-Hant/']
		,['RaidCall'			,'http://www.raidcall.com.tw/']
		,['Yahoo Messenger'		,'https://hk.messenger.yahoo.com/']
		,['QQ'				,'http://im.qq.com/']
		,['TeamSpeak'			,'http://www.teamspeak.com/']
		,['Viber'			,'http://www.viber.com/zh/']
	]]
	,['application-browser'		,'瀏覽器'		,[
		['Chrome'			,'https://www.google.com.tw/chrome/']
		,['Firefox'			,'http://mozilla.com.tw/firefox/']
		,['Opera'			,'http://www.opera.com/']
		,['Safari'			,'https://www.apple.com/tw/safari/']
		,['KKMAN'			,'http://www.kkbox.com.tw/kkman/']
		,['PCMan'			,'http://pcman.ptt.cc/']
	]]
	,['application-music'		,'線上聽音樂'		,[
		['KKBOX'			,'http://www.kkbox.com/tw/']
		,['Spotify'			,'https://www.spotify.com/tw/']
		,['iTunes'			,'https://www.apple.com/tw/itunes/download/']
		,['百度音樂'			,'http://music.baidu.com/pc/']
		,['My Radio Box'		,'http://download.ithome.com.tw/My-Radio-Box/7306']
		,['Hami+ 音樂'			,'http://hifree.hinet.net/free_listen/index.php']
	]]
	,['application-video'		,'線上看影片'		,[
		['PPS'				,'http://www.pps.tv/']
		,['風行網'			,'http://www.fun.tv/']
		,['天天看'			,'http://www.tiantiankan123.com/']
		,['皮皮'			,'http://www.pipi.cn/']
		,['西瓜影音'			,'http://www.xigua.com/']
		,['百度影音'			,'http://player.baidu.com/']
	]]
	,['application-player'		,'影片播放器'		,[
		['Potplayer'			,'https://potplayer.daum.net/']
		,['MPC-HC'			,'http://mpc-hc.org/']
		,['VLC'				,'http://www.videolan.org/vlc/']
		,['GOM Media Player'		,'http://www.gomlab.com/tw/']
		,['RealPlayer'			,'http://tw.real.com/windows/']
		,['KMPlayer'			,'http://www.kmplayer.com/']
	]]
	,['application-office'		,'辦公室'		,[
		['OpenOffice'			,'https://www.openoffice.org/zh-tw/']
		,['LibreOffice'			,'https://zh-tw.libreoffice.org/']
		,['WPS'				,'http://www.wps.cn/']
		,['AbiWord'			,'http://www.abisource.com/']
		,['PDFCreator'			,'http://www.pdfforge.org/pdfcreator']
		,['PDFCreator'			,'http://www.pdfforge.org/pdfcreator']
	]]
];

